# Generated by Django 5.2.4 on 2025-08-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0004_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grad_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
