# Generated by Django 5.2.5 on 2025-09-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0005_customuser_grad_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='grad_year',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='school',
        ),
    ]
