# Generated by Django 5.2.5 on 2025-11-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0007_remove_customuser_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
