# Generated by Django 4.2.26 on 2025-12-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0009_remove_customuser_about_customuser_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Telephone Number'),
        ),
    ]
