# Generated by Django 4.2.26 on 2026-03-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0011_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
    ]
