# Generated by Django 4.2.26 on 2026-03-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0013_otpverification_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_landlord',
            field=models.BooleanField(default=False, help_text='Grants access to the landlord dashboard. Set by admin.', verbose_name='Is Landlord'),
        ),
    ]
