# Generated by Django 4.2.26 on 2026-03-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0014_customuser_is_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tenant',
            field=models.BooleanField(default=False, help_text='Marked True automatically when a tenant accepts their invite link.', verbose_name='Is Tenant'),
        ),
    ]
