# Generated by Django 4.2.26 on 2026-03-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0015_add_is_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('sw', 'Kiswahili')], default='en', max_length=5, verbose_name='Preferred Language'),
        ),
    ]
