# Generated by Django 4.2.26 on 2025-12-02 20:12

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Jina Kamili')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Barua Pepe')),
                ('location', models.CharField(max_length=255, verbose_name='Mahali Unapoishi')),
                ('phone', models.CharField(max_length=20, verbose_name='Nambari Ya Simu')),
                ('current_situation', models.CharField(choices=[('madaftari', 'Nasimamia kutumia madaftari'), ('kompyuta', 'Nasimamia kutumia mifumo mbalimbali ya kompyuta'), ('mkabidhi', 'Nimemkabidhi mtu anisaidie kusimamia')], max_length=20, verbose_name='Hali Ya Sasa')),
                ('goals', models.CharField(choices=[('kusimamia-mwenyewe', 'Kusimamia nyumba zangu mwenyewe nikiwa na mfumo mzuri'), ('kukabidhi-mtu', 'Kukabidhi mtu asimamie nyumba yangu huku nikiwa na mfumo unaonihusha moja kwa moja')], max_length=50, verbose_name='Malengo')),
                ('challenges', models.TextField(verbose_name='Changamoto')),
                ('solution', models.TextField(blank=True, verbose_name='Njia Ya Kusaidia')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarehe Ya Kutuma')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Anwani Ya IP')),
            ],
            options={
                'verbose_name': 'Tathmini',
                'verbose_name_plural': 'Tathmini',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
