# Generated by Django 4.2.26 on 2025-12-02 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tathmini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Nambari Ya Simu')),
                ('verification_code', models.CharField(max_length=6, verbose_name='Msimbo Wa Uthibitisho')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Imehakikiwa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Imeundwa')),
                ('expires_at', models.DateTimeField(verbose_name='Inaisha')),
            ],
            options={
                'verbose_name': 'Uthibitisho Wa Simu',
                'verbose_name_plural': 'Uthibitisho Wa Simu',
            },
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nambari Ya Simu'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='verified_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tathmini.phoneverification', verbose_name='Simu Iliyohakikiwa'),
        ),
    ]
