# Generated by Django 4.2.26 on 2025-12-07 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tathmini', '0002_phoneverification_alter_assessmentsubmission_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Barua Pepe')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Imejisajili')),
            ],
            options={
                'verbose_name': 'Mteja Aliyejisajili',
                'verbose_name_plural': 'Wateja Waliyojisajili',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
