# Generated by Django 4.2.26 on 2026-03-16 01:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboardd', '0007_alter_payment_status_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'M-Pesa / Tigo Pesa / Airtel Money'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash (Deposit)')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('initiated', 'Imeanza'), ('processing', 'Inashughulikiwa'), ('submitted', 'Imewasilishwa'), ('confirmed', 'Imethibitishwa'), ('failed', 'Imeshindwa')], default='initiated', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='dashboardd.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_submissions', to='dashboardd.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Habari'), ('warning', 'Onyo'), ('success', 'Mafanikio'), ('danger', 'Hatari')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_notifications', to='dashboardd.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
