# Generated by Django 4.2.26 on 2026-03-18 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardd', '0018_remove_move_out_date_fk_tenant_user'),
        ('tenant_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('halfway', 'Halfway Through'), ('one_month', 'One Month Left'), ('two_weeks', 'Two Weeks Left'), ('daily', 'Daily (Last Week)')], max_length=20)),
                ('eligible_until', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_reminders', to='dashboardd.tenant')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('tenant', 'reminder_type', 'eligible_until')},
            },
        ),
    ]
