# Generated by Django 4.2.26 on 2025-12-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardd', '0002_property_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='lease_end_date',
            new_name='move_in_date',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='lease_start_date',
        ),
        migrations.AddField(
            model_name='tenant',
            name='move_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_profiles/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='pending', max_length=20),
        ),
    ]
