# Generated by Django 4.2.26 on 2025-12-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardd', '0003_rename_lease_end_date_tenant_move_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Chini'), ('medium', 'Wastani'), ('high', 'Juu'), ('emergency', 'Dharura')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Inasubiri'), ('in_progress', 'Inaendelea'), ('completed', 'Imekamilika'), ('cancelled', 'Imefutwa')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Fedha Taslimu'), ('check', 'Hundi'), ('bank_transfer', 'Uhamishaji wa Benki'), ('credit_card', 'Kadi ya Mkopo'), ('mobile_money', 'Pesa za Simu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Inasubiri'), ('completed', 'Imekamilika'), ('failed', 'Imeshindwa'), ('refunded', 'Imerudishwa')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'Nyumba'), ('apartment', 'Ghorofa'), ('condo', 'Kondo'), ('townhouse', 'Nyumba ya Mjini'), ('commercial', 'Biashara')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Hai'), ('pending', 'Inasubiri'), ('inactive', 'Haifanyi Kazi')], default='pending', max_length=20),
        ),
    ]
