# Generated by Django 4.2.26 on 2025-12-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardd', '0004_alter_maintenancerequest_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('nyumba', 'Nyumba'), ('ghorofa', 'Ghorofa'), ('kondo', 'Kondo'), ('nyumba_mjini', 'Nyumba ya Mjini'), ('biashara', 'Biashara')], max_length=50),
        ),
    ]
