# Generated by Django 4.2.26 on 2025-12-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardd', '0005_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('inasubiri', 'Inasubiri'), ('imekamilika', 'Imekamilika'), ('imeshindwa', 'Imeshindwa'), ('imerudishwa', 'Imerudishwa')], default='pending', max_length=50),
        ),
    ]
