# Generated by Django 4.2.26 on 2026-03-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardd', '0008_tenantinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
