# Generated by Django 4.2.26 on 2026-03-16 09:10

from django.db import migrations, models
import django.db.models.deletion


def backfill_document_versions(apps, schema_editor):
    PropertyDocument = apps.get_model('dashboardd', 'PropertyDocument')
    grouped = {}

    for doc in PropertyDocument.objects.all().order_by('property_id', 'title', 'uploaded_at', 'id'):
        key = (doc.property_id, (doc.title or '').strip().lower())
        grouped.setdefault(key, []).append(doc)

    for docs in grouped.values():
        previous = None
        version = 1
        for doc in docs:
            doc.version = version
            doc.previous_version_id = previous.id if previous else None
            doc.save(update_fields=['version', 'previous_version'])
            previous = doc
            version += 1


def reverse_backfill_document_versions(apps, schema_editor):
    PropertyDocument = apps.get_model('dashboardd', 'PropertyDocument')
    PropertyDocument.objects.all().update(version=1, previous_version=None)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardd', '0010_propertydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='dashboardd.propertydocument'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(backfill_document_versions, reverse_backfill_document_versions),
        migrations.AddConstraint(
            model_name='propertydocument',
            constraint=models.UniqueConstraint(fields=('property', 'title', 'version'), name='uniq_property_document_version'),
        ),
    ]
