# Generated by Django 4.2.26 on 2026-03-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardd', '0012_property_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
