# Generated by Django 4.2.26 on 2026-03-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardd', '0013_address_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('nyumba', 'Nyumba'), ('ghorofa', 'Ghorofa'), ('kondo', 'Kondo'), ('nyumba_mjini', 'Nyumba ya Mjini'), ('biashara', 'Biashara'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
