# Generated by Django 4.2.26 on 2026-03-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardd', '0014_unit_nullable_beds_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='amenities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('business', 'Commercial / Business'), ('other', 'Other')], max_length=50),
        ),
    ]
