# Generated by Django 4.2.26 on 2026-03-18 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardd', '0016_payment_landlord_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='min_rental_months',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of months a tenant must pay upfront.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='pending', max_length=20),
        ),
    ]
