# Generated by Django 4.2.26 on 2026-03-18 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboardd', '0017_add_min_rental_months_to_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='move_out_date',
        ),
        migrations.AddField(
            model_name='tenant',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Send eligibility/move-out reminders for this tenancy. Disable when leaving.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
